### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lita228** [GTNewHorizons/Advanced-Botany#10]
[12:54:38 ERROR]: The following problems were captured during this phase
[12:54:38 ERROR]: Caught exception from AdvancedBotany
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_372]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_372]
        at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:647) ~[OreDictionary$UnmodifiableArrayList.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at ab.common.lib.register.RecipeListAB.setupCrafting(RecipeListAB.java:195) ~[RecipeListAB.class:?]
        at ab.common.lib.register.RecipeListAB.postInit(RecipeListAB.java:138) ~[RecipeListAB.class:?]
        at ab.utils.ModHelperManager.postInit(ModHelperManager.java:20) ~[ModHelperManager.class:?]
        at ab.common.core.proxy.CommonProxy.postInit(CommonProxy.java:43) ~[CommonProxy.class:?]
        at ab.AdvancedBotany.postInit(AdvancedBotany.java:42) ~[AdvancedBotany.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744) [Loader.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
[12:54:38 ERROR]: Encountered an unexpected exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_372]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_372]
        at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:647) ~[OreDictionary$UnmodifiableArrayList.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at ab.common.lib.register.RecipeListAB.setupCrafting(RecipeListAB.java:195) ~[RecipeListAB.class:?]
        at ab.common.lib.register.RecipeListAB.postInit(RecipeListAB.java:138) ~[RecipeListAB.class:?]
        at ab.utils.ModHelperManager.postInit(ModHelperManager.java:20) ~[ModHelperManager.class:?]
        at ab.common.core.proxy.CommonProxy.postInit(CommonProxy.java:43) ~[CommonProxy.class:?]
        at ab.AdvancedBotany.postInit(AdvancedBotany.java:42) ~[AdvancedBotany.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) ~[FMLCommonHandler.class:1.7.10-NOT_A_GIT-NOT_A_GIT]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]

**Comment by Lita228** [comment]
Mod version 1.4.3

**Comment by mindbound** [comment]
Same issue here.
